spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/StoreDB.db  # Connected db address
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.damazon.config.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none	  

server:
  servlet:
    context-path: /   #If deployed change this to something specific, also change in securityConfig & Controllers

app:
  jwtSecret: "bXlKV1RTZWNyZXRLZXkxMjMh"  # Predictable key currently constant  !!IF DEPLOYED THIS NEEDS TO BE DYNAMIC, huge security breach)
  jwtExpirationInMs: 604800000  # Token Expiration: One week (in milliseconds)

