spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/StoreDB.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.damazon.config.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: com.damazon.config.SQLiteDialect
        temp:
          use_jdbc_metadata_defaults: false  # Avoid SQLite metadata issues

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    context-path: /

app:
  jwtSecret: "bXlKV1RTZWNyZXRLZXkxMjMh"  # Predictable key currently constant  !!IF DEPLOYED THIS NEEDS TO BE DYNAMIC, huge security breach)
  jwtExpirationInMs: 604800000  # Token Expiration: One week (in milliseconds)

